# Use an official openjdk runtime as a parent image
FROM openjdk:17-alpine

# Update packages and install necessary packages
RUN apk update && apk add tzdata

# Set timezone
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    echo "America/Sao_Paulo" > /etc/timezone

ENV TZ America/Sao_Paulo

# Create app directory
RUN mkdir /app

# Copy jar file to app directory
COPY authentication_api-0.0.1-SNAPSHOT.jar /app

# Run the application
CMD ["java","-Dspring.profiles.active=prod", "-Duser.timezone=America/SaoPaulo", "-Dspring.config.location=classpath:/application.properties,file:/app/config/application.properties", "-jar", "/app/authentication_api-0.0.1-SNAPSHOT.jar"]
