# Use an official openjdk runtime as a parent image
FROM openjdk:17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY authentication_api-0.0.1-SNAPSHOT.jar app.jar

# Run the application when the container starts
CMD ["java", "-jar", "app.jar"]